# Generated by Django 6.0.4 on 2026-04-27 15:20

import django.core.validators
import django.db.models.deletion
import toolbox.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable label (e.g. 'Restart App', 'Show Logs').", max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('command', models.CharField(help_text="The Dokku subcommand/args (e.g. 'ps:restart', 'logs --tail 100'). Do NOT prefix with 'dokku'; that is added automatically.", max_length=512, validators=[toolbox.models.validate_safe_command])),
                ('command_type', models.CharField(choices=[('global', 'Global'), ('app', 'App-scoped')], default='app', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Command',
                'verbose_name_plural': 'Commands',
                'ordering': ['command_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable label (e.g. 'Production VPS').", max_length=100, unique=True)),
                ('host', models.CharField(help_text="Hostname or IP address (e.g. 'dokku.example.com').", max_length=253)),
                ('ssh_user', models.CharField(default='dokku', help_text="SSH user. Dokku installations default to 'dokku'.", max_length=64)),
                ('ssh_port', models.PositiveIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('ssh_key_path', models.CharField(blank=True, help_text='Absolute path to the private key file on THIS machine. Leave blank to use the SSH agent or default key.', max_length=512)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive servers cannot be targeted for new executions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Dokku app name (must match 'dokku apps:list' output).", max_length=128, validators=[toolbox.models.validate_dokku_name])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='toolbox.server')),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
                'ordering': ['server', 'name'],
                'unique_together': {('server', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_executed', models.TextField(help_text='Full command as sent to the SSH session.')),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('error', 'Error')], default='error', max_length=10)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Wall-clock execution time in seconds.', null=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='toolbox.app')),
                ('command', models.ForeignKey(help_text='Source command template (kept even if template is deleted later).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='toolbox.command')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='toolbox.server')),
            ],
            options={
                'verbose_name': 'Execution Log',
                'verbose_name_plural': 'Execution Logs',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['-executed_at'], name='toolbox_exe_execute_37001b_idx'), models.Index(fields=['server', '-executed_at'], name='toolbox_exe_server__5a5f24_idx'), models.Index(fields=['app', '-executed_at'], name='toolbox_exe_app_id_722d68_idx'), models.Index(fields=['status'], name='toolbox_exe_status_2d291e_idx')],
            },
        ),
    ]
