# Generated by Django 6.0.4 on 2026-04-27 16:04

import django.db.models.deletion
import toolbox.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable label for this key.', max_length=100, unique=True)),
                ('key_content', models.TextField(blank=True, help_text='Private key content (PEM/OpenSSH format).')),
                ('key_path', models.CharField(blank=True, help_text='Absolute path to the private key file on this server.', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SSH Key',
                'verbose_name_plural': 'SSH Keys',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_key_path',
        ),
        migrations.AlterField(
            model_name='command',
            name='command',
            field=models.CharField(help_text="The Dokku subcommand/args (e.g. 'ps:restart', 'config:set {app} KEY=VAL'). Use '{app}' as a placeholder for the app name. If omitted, the app name is prepended.", max_length=512, validators=[toolbox.models.validate_safe_command]),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_key',
            field=models.ForeignKey(blank=True, help_text='Select an SSH key. If blank, falls back to the SSH agent or default key.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='toolbox.sshkey'),
        ),
    ]
